/*
 * File: app/store/ReminderTimes.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SimpleTasks.store.ReminderTimes', {
    extend: 'Ext.data.Store',

    requires: [
        'SimpleTasks.model.ReminderTime'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'ReminderTimes',
            model: 'SimpleTasks.model.ReminderTime',
            data: [
                {
                    num: 5,
                    timeInWords: '5 minutes'
                },
                {
                    num: 10,
                    timeInWords: '10 minutes'
                },
                {
                    num: 15,
                    timeInWords: '15 minutes'
                },
                {
                    num: 30,
                    timeInWords: '30 minutes'
                },
                {
                    num: 60,
                    timeInWords: '1 hour'
                },
                {
                    num: 120,
                    timeInWords: '2 hours'
                },
                {
                    num: 240,
                    timeInWords: '4 hours'
                },
                {
                    num: 480,
                    timeInWords: '8 hours'
                },
                {
                    num: 720,
                    timeInWords: '12 hours'
                },
                {
                    num: 1440,
                    timeInWords: '1 day'
                },
                {
                    num: 2880,
                    timeInWords: '2 days'
                },
                {
                    num: 4320,
                    timeInWords: '3 days'
                },
                {
                    num: 5760,
                    timeInWords: '4 days'
                },
                {
                    num: 10080,
                    timeInWords: '1 week'
                },
                {
                    num: 20160,
                    timeInWords: '2 weeks'
                },
                {
                    num: 30240,
                    timeInWords: '3 weeeks'
                },
                {
                    num: 40320,
                    timeInWords: '4 weeks'
                }
            ]
        }, cfg)]);
    }
});