/*
 * File: app/store/ReminderTimes.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SimpleTasks.store.ReminderTimes', {
    extend: 'Ext.data.Store',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            storeId: 'ReminderTimes',
            data: [
                [
                    5,
                    '5 minutes'
                ],
                [
                    10,
                    '10 minutes'
                ],
                [
                    15,
                    '15 minutes'
                ],
                [
                    30,
                    '30 minutes'
                ],
                [
                    60,
                    '1 hour'
                ],
                [
                    120,
                    '2 hours'
                ],
                [
                    240,
                    '4 hours'
                ],
                [
                    480,
                    '8 hours'
                ],
                [
                    720,
                    '12 hours'
                ],
                [
                    1440,
                    '1 day'
                ],
                [
                    2880,
                    '2 days'
                ],
                [
                    4320,
                    '3 days'
                ],
                [
                    5760,
                    '4 days'
                ],
                [
                    10080,
                    '1 week'
                ],
                [
                    20160,
                    '2 weeks'
                ],
                [
                    30240,
                    '3 weeeks'
                ],
                [
                    40320,
                    '4 weeks'
                ]
            ],
            fields: [
                {
                    name: 'num'
                },
                {
                    name: 'timeInWords'
                }
            ],
            proxy: {
                type: 'memory',
                reader: {
                    type: 'array'
                }
            }
        }, cfg)]);
    }
});