/*
 * File: app/model/Task.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SimpleTasks.model.Task', {
    extend: 'Ext.data.Model',
    alias: 'model.task',

    fields: [
        {
            name: 'id',
            type: 'int'
        },
        {
            name: 'title'
        },
        {
            name: 'list_id',
            type: 'int'
        },
        {
            name: 'due',
            type: 'date'
        },
        {
            name: 'reminder',
            type: 'date'
        },
        {
            defaultValue: false,
            name: 'done',
            type: 'boolean'
        },
        {
            name: 'note'
        }
    ],

    proxy: {
        type: 'localstorage',
        id: 'SimpleTasks-Task'
    }
});