/*
 * File: app/view/tasks/DefaultTimeWindow.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SimpleTasks.view.tasks.DefaultTimeWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.defaultTimeWindow',

    width: 300,
    layout: {
        type: 'fit'
    },
    closeAction: 'hide',
    title: 'Set Default Reminder Time',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    border: false,
                    frame: true,
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'timefield',
                            anchor: '100%',
                            name: 'default_time',
                            fieldLabel: 'When setting quick reminders, default the time to',
                            labelAlign: 'top'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            items: [
                                {
                                    xtype: 'tbspacer'
                                },
                                {
                                    xtype: 'button',
                                    id: 'save-default-time-btn',
                                    text: 'OK'
                                },
                                {
                                    xtype: 'button',
                                    id: 'cancel-default-time-edit-btn',
                                    text: 'Cancel'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});