/*
 * File: app/view/tasks/EditWindow.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SimpleTasks.view.tasks.EditWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.taskEditWindow',

    requires: [
        'SimpleTasks.view.tasks.Fields'
    ],

    height: 350,
    width: 500,
    layout: {
        type: 'fit'
    },
    closeAction: 'hide',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            id: 'toggle-complete-btn',
                            iconCls: 'tasks-mark-complete'
                        },
                        {
                            xtype: 'button',
                            id: 'delete-task-window-btn',
                            iconCls: 'tasks-delete-task',
                            text: 'Delete Task'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'form',
                    border: false,
                    frame: true,
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            name: 'title',
                            fieldLabel: 'Task Subject',
                            labelWidth: 80
                        },
                        {
                            xtype: 'tasksfields',
                            anchor: '100%'
                        },
                        {
                            xtype: 'component',
                            cls: 'divider'
                        },
                        {
                            xtype: 'fieldset',
                            anchor: '100%',
                            border: false,
                            margin: '0 0 5',
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    margin: '0 5 0 0',
                                    name: 'has_reminder',
                                    boxLabel: 'Reminder'
                                },
                                {
                                    xtype: 'datefield',
                                    disabled: true,
                                    margin: '0 5 0 0',
                                    name: 'reminder_date',
                                    editable: false
                                },
                                {
                                    xtype: 'timefield',
                                    disabled: true,
                                    name: 'reminder_time',
                                    editable: false
                                }
                            ]
                        },
                        {
                            xtype: 'htmleditor',
                            anchor: '100% -90',
                            height: 150,
                            name: 'note'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            name: 'reminder',
                            fieldLabel: 'Label'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            name: 'done',
                            fieldLabel: 'Label'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            items: [
                                {
                                    xtype: 'tbspacer',
                                    flex: 1
                                },
                                {
                                    xtype: 'button',
                                    id: 'save-task-edit-btn',
                                    text: 'Save'
                                },
                                {
                                    xtype: 'button',
                                    id: 'cancel-task-edit-btn',
                                    text: 'Cancel'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});