/*
 * File: app/view/tasks/Grid.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SimpleTasks.view.tasks.Grid', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.taskGrid',

    requires: [
        'SimpleTasks.view.override.tasks.Grid'
    ],

    height: 250,
    width: 400,
    enableColumnHide: false,
    enableColumnMove: false,
    enableColumnResize: false,
    store: 'Tasks',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'datecolumn',
                    text: 'SomeColumns'
                }
            ]
        });

        me.callParent(arguments);
    }

});