/*
 * File: app/view/lists/ContextMenu.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SimpleTasks.view.lists.ContextMenu', {
    extend: 'Ext.menu.Menu',
    alias: 'widget.listsContextMenu',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'menuitem',
                    id: 'new-list-item',
                    iconCls: 'tasks-new-list',
                    text: 'New List'
                },
                {
                    xtype: 'menuitem',
                    id: 'new-folder-item',
                    iconCls: 'tasks-new-folder',
                    text: 'New Folder'
                },
                {
                    xtype: 'menuitem',
                    id: 'new-task-item',
                    iconCls: 'tasks-new',
                    text: 'New Task'
                },
                {
                    xtype: 'menuitem',
                    id: 'delete-folder-item',
                    iconCls: 'tasks-delete-folder',
                    text: 'Delete'
                },
                {
                    xtype: 'menuitem',
                    id: 'delete-list-item',
                    iconCls: 'tasks-delete-list',
                    text: 'Delete'
                }
            ]
        });

        me.callParent(arguments);
    },

    setList: function(list) {
        this.list = list;
    },

    getList: function() {
        return this.list;
    }

});